# Generated by Django 5.2.3 on 2025-07-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
