# Generated by Django 5.2.3 on 2025-07-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatmessage_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
